import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";
import Nav from "./components/Nav/nav";

export const metadata: Metadata = {
  title: "Teste técnico",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="pt-br">
      <body className="bg-yellow-300">
        <Nav/>
        <Toaster position="bottom-center" />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
